version: "3.7"

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    networks:
      - default

  ocr-api:
    build: .
    container_name: ocr
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - default
    restart: "unless-stopped"
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  redis_data:
